const $ = s => document.querySelector(s);
const KEYS = { memories: 'nami.memories.v1', history: 'nami.history.v1' };
let memories = JSON.parse(localStorage.getItem(KEYS.memories) || '[]');
let history = JSON.parse(localStorage.getItem(KEYS.history) || '[]');
let recognition, listening = false;
const chat = $('#chat');
function save(){localStorage.setItem(KEYS.memories, JSON.stringify(memories));localStorage.setItem(KEYS.history, JSON.stringify(history));renderMemory();}
function clock(){ $('#clock').textContent = new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}); } clock();setInterval(clock,1000);
function addMessage(role,text,saveIt=true){const node=$('#messageTemplate').content.firstElementChild.cloneNode(true);node.classList.add(role);node.querySelector('.meta').textContent=role==='nami'?'✦ NAMI // LOCAL ASSISTANT':'● YOU';node.querySelector('.message-text').textContent=text;if(role==='nami'){const b=document.createElement('button');b.textContent='CORRECT / TEACH NAMI';b.onclick=()=>learnCorrection(text);node.querySelector('.message-actions').append(b)}chat.append(node);chat.scrollTop=chat.scrollHeight;if(saveIt){history.push({role,text});history=history.slice(-80);save();}if(role==='nami'&&$('#ttsToggle').checked)speak(text)}
function renderMemory(){ $('#memoryCount').textContent=`${memories.length} ${memories.length===1?'entry':'entries'}`;const list=$('#memoryList');list.innerHTML='';if(!memories.length){list.innerHTML='<div class="memory-item">Nothing saved yet. Tell Nami a preference or correct a response.</div>';return}memories.slice().reverse().slice(0,8).forEach(m=>{const el=document.createElement('div');el.className='memory-item';el.innerHTML=`<b>${m.type.toUpperCase()}</b><br>`;el.append(document.createTextNode(m.text));list.append(el)})}
function learnCorrection(reply){const correction=prompt('What should Nami remember or say instead?');if(!correction?.trim())return;memories.push({type:'correction',text:`Instead of “${reply.slice(0,90)}${reply.length>90?'…':''}”, prefer: ${correction.trim()}`,at:Date.now()});save();addMessage('nami',`Saved locally. I’ll use that correction as a preference in future chats in this browser.`)}
function rememberFrom(text){const match=text.match(/(?:remember (?:that )?|my (?:favorite|favourite) |i prefer |call me )(.+)/i);if(match){memories.push({type:'preference',text:match[1].trim(),at:Date.now()});save();return `I’ve saved that locally: “${match[1].trim()}”. You can review or reset it in my Learning Cache.`}return null}
function answer(text){const saved=rememberFrom(text);if(saved)return saved;const t=text.toLowerCase();if(/what do you remember|\/memory/.test(t)){return memories.length?`Here’s my local learning cache:\n${memories.map((m,i)=>`${i+1}. ${m.text}`).join('\n')}\n\nThis is browser-only preference/correction memory, not model training.`:'I don’t have any saved preferences yet. You can say “remember that…” or correct one of my replies.'}if(/help.*(?:organize|plan)|\/plan/.test(t))return 'Try this desktop-sized plan:\n1. Pick one outcome for today.\n2. Do a 25-minute focus block.\n3. Write the next physical action before you stop.\n\nTell me what you’re working on and I’ll tailor it.';if(/fun fact|\/fact/.test(t))return 'Fun fact: the first web page is still online. I’m less immortal, but I do keep the local notes you choose to teach me.';if(/hello|hi |hey/.test(t))return 'Hello! I’m Nami, your local-first desktop assistant. I can chat, speak where your browser supports it, and remember corrections you make.';const recentCorrection=memories.filter(m=>m.type==='correction').at(-1);return `I’m running in a static, no-API-key mode, so I use helpful desktop-style responses rather than a cloud model. ${recentCorrection?`I’m also keeping your latest correction in mind.`:'You can teach me preferences by saying “remember that…” or using CORRECT / TEACH NAMI.'}`}
function send(text){text=text.trim();if(!text)return;addMessage('user',text);setTimeout(()=>addMessage('nami',answer(text)),220)}
function speak(text){if(!('speechSynthesis'in window)){notice('Text-to-speech is not available in this browser.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.98;u.pitch=1.08;speechSynthesis.speak(u)}
function notice(text){const n=$('#speechNotice');n.textContent=text;n.hidden=false}
function setupSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#voiceStatus').textContent='unavailable';notice('Voice input is unavailable here. You can still type, and text-to-speech may work.');return}recognition=new SR();recognition.lang='en-US';recognition.interimResults=false;recognition.onstart=()=>{listening=true;$('#micButton').classList.add('listening');$('#voiceStatus').textContent='listening'};recognition.onend=()=>{listening=false;$('#micButton').classList.remove('listening');$('#voiceStatus').textContent='ready'};recognition.onerror=e=>{notice(`Voice input: ${e.error}. Check microphone permission and try again.`)};recognition.onresult=e=>{const spoken=e.results[0][0].transcript;$('#messageInput').value=spoken;send(spoken)};$('#micDot').classList.add('green');$('#voiceStatus').textContent='ready'}
$('#chatForm').onsubmit=e=>{e.preventDefault();send($('#messageInput').value);$('#messageInput').value=''};$('#micButton').onclick=()=>{if(!recognition)return;listening?recognition.stop():recognition.start()};$('#clearChat').onclick=()=>{history=[];localStorage.setItem(KEYS.history,'[]');chat.innerHTML='';addMessage('nami','Conversation cleared. Your Learning Cache remains intact.',false)};$('#resetMemory').onclick=()=>{if(confirm('Erase all of Nami’s local preference and correction memory?')){memories=[];save();addMessage('nami','Learning Cache reset. I’ve forgotten the saved local preferences.',false)}};$('#exportMemory').onclick=()=>{const blob=new Blob([JSON.stringify(memories,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nami-learning-cache.json';a.click();URL.revokeObjectURL(a.href)};document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>send(b.dataset.prompt));renderMemory();setupSpeech();if(history.length)history.forEach(m=>addMessage(m.role,m.text,false));else addMessage('nami','Boot complete. I’m Nami. Ask me anything, tap the microphone, or teach me a preference to remember locally.',false);
